; 10BASE-T transmitter (10 Mbit/s Manchester, IEEE 802.3 clause 14), one
; thread, on the serializer engine (docs/SERIALIZER.md, SEMANTICS 15).
; Start thread 0 at address 0; thread 1 is not used. Transmit only: the
; engine's receiver is off and nothing is decoded from the line (receive
; would need a second pair, the receiver on, and a 10BASE-T clock recovery
; that four samples per bit at 40 MHz cannot give; out of scope).
;
; Pins: TX+ = uio0 (pair 0 P), TX- = uio1 (pair 0 N), both push-pull
; outputs from the first instructions on. SERCFG ETHCFG = 0x0A: Manchester,
; CRC-32, receiver off, pair 0.
;
; Clock. CLK_KHZ = 40000: SYMT = 2 cycles per half-bit (50 ns). CLK_KHZ =
; 20000 also works: SYMT = 1, and every byte still fits its 8 slots (below).
; Other clocks are not 10BASE-T (a half-bit must be a whole number of
; cycles: 50 MHz would need 2.5).
;
; What goes on the wire.
;   Idle: both pins low (zero differential), and a normal link pulse every
;   LP_PERIOD * LP_TICKS cycles = 16 ms (64 ticks of 250 us; measured 16 ms
;   + 12 cycles): TX+ high, TX- low for 4 cycles at 40 MHz (2 at 20 MHz),
;   100 ns. The interval restarts with every pulse and every frame: the
;   first pulse after a frame comes 16 ms after the end of its gap, about
;   16.01 ms after its start of idle (802.3 14.2.1.1: 16 +- 8 ms after the
;   start of TP_IDL and between pulses). After a pulse no frame starts for
;   one idle tick (250 us); that spacing is this firmware's choice, the
;   standard states none.
;   A frame: 7 bytes 0x55, SFD 0xD5 (outside the CRC), then in the CRC:
;     destination ff:ff:ff:ff:ff:ff (broadcast)
;     source      02:4b:45:59:45:52 (locally administered: 02 "KEYER")
;     EtherType   0x88B5 (IEEE 802 local experimental EtherType 1)
;     payload     [cmd, d1 .. dN, generated bytes]
;     FCS         CRC-32, appended by the engine
;   then the engine's start of idle: TX+ high for 6 half-bit periods after
;   the last half-bit, so 300 ns of positive level after the last bit cell;
;   counted from the last rising edge, 300 ns after a final 0 and 350 ns
;   after a final 1 (802.3 14.3.1.2.1: at least 250 ns; the receiver model
;   also holds it under 450 ns). Then the pair is driven low, and IFG = 192
;   half-bits (96 bit times, 9.6 us) of silence are counted from the end of
;   the start of idle before anything else. Measured frame to frame: 11.55
;   us from the end of the last bit cell to the next frame's first symbol
;   (96 bit times + the 300 ns tail + 1.65 us of firmware between the gap
;   and the next frame's first byte).
;
; Host interface. The host stages a whole 16-byte block in INBOX0 (one
; SPI write of 16 bytes); a frame starts only when the inbox is full, so
; nothing the host does later can starve a frame in flight, however slow
; its SPI clock (a byte takes 800 ns on the wire; SPI at clk/8 delivers one
; every 1.6 us at best).
;   byte 0  cmd: bits 3:0 N = staged data bytes to send (0..15),
;           bits 7:4 K = generated blocks: K = 0 pads with zeros to the
;           46-byte minimum payload; K > 0 appends 96*K bytes of a counting
;           pattern 00 01 02 .. FF 00 .. (and needs no padding).
;   bytes 1..15  d1..d15; only the first N are sent, the other 15 - N are
;           popped and dropped while the first generated bytes go out.
; The payload's first byte is cmd itself, so a receiver can find N and K
; in a padded frame. Payload length = 1 + N + 96 K if K > 0, else 46.
; Longest: cmd 0xFF, 1 + 15 + 1440 = 1456 bytes (frame 1474 bytes with the
; FCS; the 802.3 maximum is 1518). Shortest: 46 (frame 64).
; A host that stages fewer than 16 bytes gets no frame (and link pulses go
; on); the block is sent when its 16th byte arrives.
; Completion: after the gap, PUSHNB cmd into OUTBOX0 (dropped if the outbox
; is full: the transmitter never waits for the SPI host). The next block
; may be staged as soon as there is room: the whole block has left the
; inbox by the 38th byte of a frame (cmd, N data, 15 - N drops), so a host
; that stages the next block while a frame is on the wire gets it sent
; after the minimum gap.
;
; Underrun budget (from the listing; slots are thread 0's, 2 cycles each).
;   The engine takes the holding register once per byte: every 16 symbol
;   ticks = 32 cycles = 16 slots at 40 MHz (8 at 20 MHz). Each SERI/SERIC/
;   SERTXC blocks until the holding register is free, i.e. until just after
;   the engine took the previous byte, and the next byte must be in it
;   before the next take. So nothing underruns if, from each byte-queueing
;   instruction to the next, there are at most 16 slots (8 at 20 MHz) in
;   every loop; a single longer stretch after a byte that was waited for is
;   allowed up to about 30 slots (14 at 20 MHz), because the holding
;   register already holds the next byte. Slots from one byte-queueing
;   instruction to the next, the next included:
;     preamble, SFD, header: seri / seric in a row               1
;     cmd -> first data (N > 0): beq, pop, sertxc                3
;     cmd -> gen1 (N = 0): beq, mov, beq, sertxc                 4
;     data loop: djnz, pop, sertxc                               3
;     last data -> gen1: djnz, mov, beq, sertxc                  4
;     last data -> gen (N = 15): djnz, mov, beq, mov, sertxc     5
;     gen1 loop (drops a staged byte): add, pop, djnz, sertxc    4
;     last gen1 -> gen: add, pop, djnz, mov, sertxc              5
;     gen loop: add, djnz, sertxc                                3
;   The worst is 5 slots: every queueing instruction after the first two
;   of a frame waits at least 11 slots for the engine at 40 MHz, 3 at
;   20 MHz, and the holding register is never empty for more than 2 cycles
;   inside a frame (test_fw_eth_10bt_tx measures both over a 1474-byte
;   frame). The preamble is straight-line code so that Z still holds
;   (N = 0) at hdr_end: nothing between them writes a flag.
;
; Why one thread. The link-pulse timer and the frame use thread 0's one
; timer in turn: SETT LP_PERIOD while idle (NOW counts 250 us ticks), SETT
; SYMT for a frame (NOW counts half-bits, the engine's symbol period, and
; the gap is a WAITD on that grid). A pulse is written only from the idle
; loop, and the idle loop is entered only after SERWT (the engine has
; finished its tail and driven both pins low) and the gap; while the
; engine sends, thread 0 is in the frame code, which has no pin
; instruction. So the engine and the pin instructions never drive the pair
; in the same period, by construction rather than by a handshake. Thread 1
; stays free, and nothing can drive the pair while it is in use.
;
; Registers: r0 cmd; r1 scratch, dropped bytes; r2 loop count; r3
; generated byte; r4 15 - N; r5 the generated count after the drop loop
; (96 K - (15 - N), or 30); r6 LP_PERIOD; r7 pattern increment (1 or 0)
; during a frame, PULSE_HOLD while idle.
;
; Size: 88 words.

.equ CLK_KHZ,    40000              ; core clock
.equ SYMT,       CLK_KHZ / 20000    ; cycles per half-bit: 2 at 40 MHz, 1 at 20 MHz
.equ LP_PERIOD,  CLK_KHZ / 4        ; idle timer tick, cycles: 250 us
.equ LP_TICKS,   64                 ; link pulse every 64 idle ticks: 16 ms
.equ PULSE_HOLD, SYMT - 1           ; 1: the pulse lasts 4 cycles, 0: 2 cycles (100 ns)
.equ IFG,        192                ; half-bits of silence after a frame: 96 bit times
.equ ETHCFG,     0x0A               ; SERCFG: Manchester | CRC-32 | pair 0
.equ TXP, uio0                      ; TX+ = pair 0 P
.equ TXN, uio1                      ; TX- = pair 0 N

init:   clr   TXP                   ; both low: zero differential
        clr   TXN
        oen   TXP
        oen   TXN
        ldi   r1, ETHCFG
        sercfg r1                   ; thread 0 owns the engine
        ldw   r6, LP_PERIOD
        ldi   r7, PULSE_HOLD
restart: sett r6                    ; idle: NOW counts LP_PERIOD cycles
        setd  LP_TICKS
idle:   rds   r1
        andi  r1, 2                 ; inbox full: a whole block is staged
        bne   frame
        bdr   pulse
        bra   idle

pulse:  set   TXP                   ; TX+ high, TX- stays low
        outr  TXP, r7               ; 40 MHz: still high; 20 MHz: low already
        clr   TXP
        sett  r6
        waitd 1                     ; no frame for one idle tick after a pulse
        setd  LP_TICKS - 1          ; next pulse LP_TICKS ticks after this one
        bra   idle

frame:  pop   r0                    ; cmd
        mov   r1, r0
        andi  r1, 15                ; N
        ldi   r4, 15
        sub   r4, r1                ; 15 - N: staged bytes to drop
        mov   r5, r0
        andi  r5, 0xF0              ; 16 K
        ldi   r7, 1                 ; counting pattern
        beq   padlen
        mov   r1, r5
        shl   r5
        add   r5, r1                ; 48 K
        shl   r5                    ; 96 K
        sub   r5, r4                ; 96 K - (15 - N) after the drop loop
        bra   go
padlen: ldi   r5, 30                ; (45 - N) - (15 - N): payload of 46
        ldi   r7, 0                 ; constant 0
go:     ldi   r3, 0
        ldi   r1, SYMT
        sett  r1                    ; NOW counts half-bits from here
        mov   r2, r0
        andi  r2, 15                ; r2 = N, and Z = (N = 0) until hdr_end:
pre:    seri  0x55                  ; nothing from here to there writes a flag
        seri  0x55
        seri  0x55
        seri  0x55
        seri  0x55
        seri  0x55
        seri  0x55                  ; preamble
        seri  0xD5                  ; SFD
hdr:    seric 0xFF                  ; destination: broadcast
        seric 0xFF
        seric 0xFF
        seric 0xFF
        seric 0xFF
        seric 0xFF
        seric 0x02                  ; source 02:4b:45:59:45:52
        seric 0x4B
        seric 0x45
        seric 0x59
        seric 0x45
        seric 0x52
        seric 0x88                  ; EtherType 0x88B5
        seric 0xB5
hdr_end: sertxc r0                  ; payload byte 0: cmd
        beq   nodata
data:   pop   r1                    ; the block is complete: never blocks
        sertxc r1
        djnz  r2, data
nodata: mov   r2, r4
        beq   gen2                  ; N = 15: nothing to drop
gen1:   sertxc r3                   ; generated byte, and one unused staged
        add   r3, r7                ; byte dropped, so that the host can stage
        pop   r1                    ; the next block during this frame
        djnz  r2, gen1
gen2:   mov   r2, r5
gen:    sertxc r3                   ; the rest of the pattern or padding
        add   r3, r7
        djnz  r2, gen
        serwt                       ; FCS, start of idle, pair low
        setd  IFG
        waitd 0                     ; 96 bit times of silence
        pushnb r0                   ; done: cmd to the host
        ldi   r7, PULSE_HOLD
        bra   restart
