// Generated by tools/keyer_isa.py. Do not edit.
`ifndef KEYER_ISA_VH
`define KEYER_ISA_VH
`define KEYER_ISA_VERSION 8'd1

`define KEYER_MAJ_ALU2  4'h0
`define KEYER_MAJ_ALU1  4'h1
`define KEYER_MAJ_ADDI  4'h2
`define KEYER_MAJ_ANDI  4'h3
`define KEYER_MAJ_ORI   4'h4
`define KEYER_MAJ_XORI  4'h5
`define KEYER_MAJ_LDI   4'h6
`define KEYER_MAJ_LDIH  4'h7
`define KEYER_MAJ_CMPI  4'h8
`define KEYER_MAJ_BCC   4'h9
`define KEYER_MAJ_BPIN  4'hA
`define KEYER_MAJ_JMP   4'hB
`define KEYER_MAJ_PIN   4'hC
`define KEYER_MAJ_PINR  4'hD
`define KEYER_MAJ_XFER  4'hE
`define KEYER_MAJ_MISC  4'hF

`define KEYER_ADD     4'd0  // major 0: rd = rd + rs
`define KEYER_SUB     4'd1  // major 0: rd = rd - rs
`define KEYER_AND     4'd2  // major 0: rd = rd & rs
`define KEYER_OR      4'd3  // major 0: rd = rd | rs
`define KEYER_XOR     4'd4  // major 0: rd = rd ^ rs
`define KEYER_MOV     4'd5  // major 0: rd = rs
`define KEYER_CMP     4'd6  // major 0: flags(rd - rs)
`define KEYER_TST     4'd7  // major 0: flags(rd & rs)
`define KEYER_ADC     4'd8  // major 0: rd = rd + rs + C
`define KEYER_SBC     4'd9  // major 0: rd = rd - rs - C
`define KEYER_SHL     4'd0  // major 1: C = rd[15]; rd <<= 1
`define KEYER_SHR     4'd1  // major 1: C = rd[0]; rd >>= 1
`define KEYER_RCL     4'd2  // major 1: rotate left through carry
`define KEYER_RCR     4'd3  // major 1: rotate right through carry
`define KEYER_NOT     4'd4  // major 1: rd = ~rd
`define KEYER_NEG     4'd5  // major 1: rd = -rd
`define KEYER_INC     4'd6  // major 1: rd = rd + 1
`define KEYER_DEC     4'd7  // major 1: rd = rd - 1
`define KEYER_SWAP    4'd8  // major 1: swap bytes
`define KEYER_REV8    4'd9  // major 1: bit-reverse low byte
`define KEYER_DJNZ    4'd10  // major 1: rd -= 1; if rd != 0: PC = PC+1+off (flags unchanged)
`define KEYER_BRA     3'd0  // major 9: branch if always
`define KEYER_BEQ     3'd1  // major 9: branch if Z=1
`define KEYER_BNE     3'd2  // major 9: branch if Z=0
`define KEYER_BCS     3'd3  // major 9: branch if C=1
`define KEYER_BCC     3'd4  // major 9: branch if C=0
`define KEYER_BFE     3'd5  // major 9: branch if inbox empty
`define KEYER_BFNE    3'd6  // major 9: branch if inbox not empty
`define KEYER_BTP     3'd7  // major 9: branch if timer tick pending
`define KEYER_BP0     1'd0  // major A: branch if level[pin]=0
`define KEYER_BP1     1'd1  // major A: branch if level[pin]=1
`define KEYER_JMP     1'd0  // major B: PC = addr
`define KEYER_CALL    1'd1  // major B: LR = PC+1; PC = addr
`define KEYER_SET     4'd0  // major C: pinwrite(p, 1)
`define KEYER_CLR     4'd1  // major C: pinwrite(p, 0)
`define KEYER_OEN     4'd2  // major C: PP: uio_oe[p] = 1
`define KEYER_OEF     4'd3  // major C: PP: uio_oe[p] = 0
`define KEYER_OD      4'd4  // major C: pin mode = open-drain
`define KEYER_PP      4'd5  // major C: pin mode = push-pull
`define KEYER_WT0     4'd6  // major C: wait level[p] = 0
`define KEYER_WT1     4'd7  // major C: wait level[p] = 1
`define KEYER_WTR     4'd8  // major C: wait rising edge
`define KEYER_WTF     4'd9  // major C: wait falling edge
`define KEYER_WRC     4'd10  // major C: pinwrite(p, C)
`define KEYER_RDC     4'd11  // major C: C = level[p]
`define KEYER_TSTP    4'd12  // major C: Z = (level[p] == 0)
`define KEYER_OUTR    3'd0  // major D: pinwrite(p, rs[0])
`define KEYER_INR     3'd1  // major D: rd = level[p]
`define KEYER_PUSH    4'd0  // major E: outbox <- rs[7:0]
`define KEYER_POP     4'd1  // major E: rd = inbox byte
`define KEYER_RDS     4'd2  // major E: rd = status
`define KEYER_RDCYC   4'd3  // major E: rd = cycle counter
`define KEYER_SETT    4'd4  // major E: timer period = rs; restart
`define KEYER_RDT     4'd5  // major E: rd = timer count
`define KEYER_PUSHNB  4'd6  // major E: non-blocking push, C = success
`define KEYER_POPNB   4'd7  // major E: non-blocking pop, C = success
`define KEYER_OUTB    4'd8  // major E: pinwrite(i, rs[i]) for uio
`define KEYER_INB     4'd9  // major E: rd = level[7:0]
`define KEYER_INW     4'd10  // major E: rd = level[15:0]
`define KEYER_OUTOE   4'd11  // major E: PP pins: uio_oe = rs[7:0]
`define KEYER_RDLR    4'd12  // major E: rd = LR
`define KEYER_JMPR    4'd13  // major E: PC = rs
`define KEYER_NOP     4'd0  // major F: nothing
`define KEYER_HALT    4'd1  // major F: stop this thread
`define KEYER_RET     4'd2  // major F: PC = LR
`define KEYER_WAITT   4'd3  // major F: wait timer tick, clear it
`define KEYER_DELAY   4'd4  // major F: occupy 1+n slots
`define KEYER_SETC    4'd5  // major F: C = 1
`define KEYER_CLC     4'd6  // major F: C = 0
`define KEYER_START   4'd7  // major F: start other thread
`define KEYER_STOP    4'd8  // major F: stop other thread
`define KEYER_CLRT    4'd9  // major F: clear timer tick

`define KEYER_COND_RA   3'd0
`define KEYER_COND_EQ   3'd1
`define KEYER_COND_NE   3'd2
`define KEYER_COND_CS   3'd3
`define KEYER_COND_CC   3'd4
`define KEYER_COND_FE   3'd5
`define KEYER_COND_FNE  3'd6
`define KEYER_COND_TP   3'd7

`endif
