// Generated by tools/loom_isa.py. Do not edit.
`ifndef LOOM_ISA_VH
`define LOOM_ISA_VH
`define LOOM_ISA_VERSION 8'd1

`define LOOM_MAJ_ALU2  4'h0
`define LOOM_MAJ_ALU1  4'h1
`define LOOM_MAJ_ADDI  4'h2
`define LOOM_MAJ_ANDI  4'h3
`define LOOM_MAJ_ORI   4'h4
`define LOOM_MAJ_XORI  4'h5
`define LOOM_MAJ_LDI   4'h6
`define LOOM_MAJ_LDIH  4'h7
`define LOOM_MAJ_CMPI  4'h8
`define LOOM_MAJ_BCC   4'h9
`define LOOM_MAJ_BPIN  4'hA
`define LOOM_MAJ_JMP   4'hB
`define LOOM_MAJ_PIN   4'hC
`define LOOM_MAJ_PINR  4'hD
`define LOOM_MAJ_XFER  4'hE
`define LOOM_MAJ_MISC  4'hF

`define LOOM_ADD     4'd0  // major 0: rd = rd + rs
`define LOOM_SUB     4'd1  // major 0: rd = rd - rs
`define LOOM_AND     4'd2  // major 0: rd = rd & rs
`define LOOM_OR      4'd3  // major 0: rd = rd | rs
`define LOOM_XOR     4'd4  // major 0: rd = rd ^ rs
`define LOOM_MOV     4'd5  // major 0: rd = rs
`define LOOM_CMP     4'd6  // major 0: flags(rd - rs)
`define LOOM_TST     4'd7  // major 0: flags(rd & rs)
`define LOOM_ADC     4'd8  // major 0: rd = rd + rs + C
`define LOOM_SBC     4'd9  // major 0: rd = rd - rs - C
`define LOOM_SHL     4'd0  // major 1: C = rd[15]; rd <<= 1
`define LOOM_SHR     4'd1  // major 1: C = rd[0]; rd >>= 1
`define LOOM_RCL     4'd2  // major 1: rotate left through carry
`define LOOM_RCR     4'd3  // major 1: rotate right through carry
`define LOOM_NOT     4'd4  // major 1: rd = ~rd
`define LOOM_NEG     4'd5  // major 1: rd = -rd
`define LOOM_INC     4'd6  // major 1: rd = rd + 1
`define LOOM_DEC     4'd7  // major 1: rd = rd - 1
`define LOOM_SWAP    4'd8  // major 1: swap bytes
`define LOOM_REV8    4'd9  // major 1: bit-reverse low byte
`define LOOM_DJNZ    4'd10  // major 1: rd -= 1; if rd != 0: PC = PC+1+off (flags unchanged)
`define LOOM_BRA     3'd0  // major 9: branch if always
`define LOOM_BEQ     3'd1  // major 9: branch if Z=1
`define LOOM_BNE     3'd2  // major 9: branch if Z=0
`define LOOM_BCS     3'd3  // major 9: branch if C=1
`define LOOM_BCC     3'd4  // major 9: branch if C=0
`define LOOM_BFE     3'd5  // major 9: branch if inbox empty
`define LOOM_BFNE    3'd6  // major 9: branch if inbox not empty
`define LOOM_BTP     3'd7  // major 9: branch if timer tick pending
`define LOOM_BP0     1'd0  // major A: branch if level[pin]=0
`define LOOM_BP1     1'd1  // major A: branch if level[pin]=1
`define LOOM_JMP     1'd0  // major B: PC = addr
`define LOOM_CALL    1'd1  // major B: LR = PC+1; PC = addr
`define LOOM_SET     4'd0  // major C: pinwrite(p, 1)
`define LOOM_CLR     4'd1  // major C: pinwrite(p, 0)
`define LOOM_OEN     4'd2  // major C: PP: uio_oe[p] = 1
`define LOOM_OEF     4'd3  // major C: PP: uio_oe[p] = 0
`define LOOM_OD      4'd4  // major C: pin mode = open-drain
`define LOOM_PP      4'd5  // major C: pin mode = push-pull
`define LOOM_WT0     4'd6  // major C: wait level[p] = 0
`define LOOM_WT1     4'd7  // major C: wait level[p] = 1
`define LOOM_WTR     4'd8  // major C: wait rising edge
`define LOOM_WTF     4'd9  // major C: wait falling edge
`define LOOM_WRC     4'd10  // major C: pinwrite(p, C)
`define LOOM_RDC     4'd11  // major C: C = level[p]
`define LOOM_TSTP    4'd12  // major C: Z = (level[p] == 0)
`define LOOM_OUTR    3'd0  // major D: pinwrite(p, rs[0])
`define LOOM_INR     3'd1  // major D: rd = level[p]
`define LOOM_PUSH    4'd0  // major E: outbox <- rs[7:0]
`define LOOM_POP     4'd1  // major E: rd = inbox byte
`define LOOM_RDS     4'd2  // major E: rd = status
`define LOOM_RDCYC   4'd3  // major E: rd = cycle counter
`define LOOM_SETT    4'd4  // major E: timer period = rs; restart
`define LOOM_RDT     4'd5  // major E: rd = timer count
`define LOOM_PUSHNB  4'd6  // major E: non-blocking push, C = success
`define LOOM_POPNB   4'd7  // major E: non-blocking pop, C = success
`define LOOM_OUTB    4'd8  // major E: pinwrite(i, rs[i]) for uio
`define LOOM_INB     4'd9  // major E: rd = level[7:0]
`define LOOM_INW     4'd10  // major E: rd = level[15:0]
`define LOOM_OUTOE   4'd11  // major E: PP pins: uio_oe = rs[7:0]
`define LOOM_RDLR    4'd12  // major E: rd = LR
`define LOOM_JMPR    4'd13  // major E: PC = rs
`define LOOM_NOP     4'd0  // major F: nothing
`define LOOM_HALT    4'd1  // major F: stop this thread
`define LOOM_RET     4'd2  // major F: PC = LR
`define LOOM_WAITT   4'd3  // major F: wait timer tick, clear it
`define LOOM_DELAY   4'd4  // major F: occupy 1+n slots
`define LOOM_SETC    4'd5  // major F: C = 1
`define LOOM_CLC     4'd6  // major F: C = 0
`define LOOM_START   4'd7  // major F: start other thread
`define LOOM_STOP    4'd8  // major F: stop other thread
`define LOOM_CLRT    4'd9  // major F: clear timer tick

`define LOOM_COND_RA   3'd0
`define LOOM_COND_EQ   3'd1
`define LOOM_COND_NE   3'd2
`define LOOM_COND_CS   3'd3
`define LOOM_COND_CC   3'd4
`define LOOM_COND_FE   3'd5
`define LOOM_COND_FNE  3'd6
`define LOOM_COND_TP   3'd7

`endif
